name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create version.txt
        run: |
          export PACKAGE_JSON_VERSION=$(cat src/package.json | jq -r .version)
          export VERSION=$PACKAGE_JSON_VERSION.${GITHUB_RUN_ID}
          echo $VERSION > version.txt
          echo $VERSION
      
      - name: Upload version.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
      

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          IMAGE_NAME: nodejs-app
        run: |
          export VERSION=$(cat version.txt)
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$VERSION ./src
          docker push $ECR_REGISTRY/$IMAGE_NAME:$VERSION
      
      - name: Update ECS Service
        run: |
          aws ecs describe-task-definition \
          --task-definition ecr-td-nodejs-app \
          --query 'taskDefinition' \
          > task-definition.json
    
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:    
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Configure AWS Credentials
  #     uses: aws-actions/configure-aws-credentials@v4
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: ${{ secrets.AWS_REGION }}
  #   - name: Create version.txt
  #     run: |
  #       export PACKAGE_JSON_VERSION=$(cat src/package.json | jq -r .version)
  #       export VERSION=$PACKAGE_JSON_VERSION.${GITHUB_RUN_ID}
  #       echo $VERSION > version.txt
  #       echo $VERSION
      
  #   - name: Upload version.txt as artifact
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: version
  #       path: version.txt
  #   - name: Update ECS Service with new image
  #     run: |
  #       export VERSION=$(cat version.txt)
  #       export IMAGE=$ECR_REGISTRY/$IMAGE_NAME:$VERSION
  #       aws ecs update-service --cluster dev-cluster --service nodejs-web --task-definition '{"containerDefinitions":[{"name":"ecr-td-nodejs-app","image":"'"$IMAGE"'","cpu":256,"memory":512,"portMappings":[{"containerPort":3000,"hostPort":80,"protocol":"tcp"}]}]}'